arch:
 - amd64
 - ppc64le
 
language: node_js
node_js:
  - "1"

services: mongodb

before_install:
  - $SHELL --version 2> /dev/null || dpkg -s $SHELL 2> /dev/null || which $SHELL
  - curl --version
  - wget --version
  - shellcheck --version
install:
  - if [ -z "${SHELLCHECK-}" ]; then nvm install node && npm install && npm prune && npm ls urchin doctoc eclint dockerfile_lint; fi
  - '[ -z "$WITHOUT_CURL" ] || sudo apt-get remove curl -y'

before_script:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
